onCreate:
  - sudo snap install flutter --classic
  - yes | flutter doctor --android-licenses
onStart:
  - |
        printf "\ninstall flutter extension in vscode\n\n"
        printf "GO TO dashboard and open the GUI by clicking GUI icon under more options of the workspace\n\n"
        printf "open android studio and create AVD and then run it\n\n"
        printf "then, to run the flutter project, run the following command\n\n"
        printf "flutter run"
